Repository jupyterlite/terminal, pull requests merged in 2024-10, with the labels that each got.

#27 Obtain wasm packages from emscripten-forge when building deployment
  .github/workflows/deploy.yml
  .gitignore
  cockle-config-in.json
  jupyterlite_terminal/add_on.py
  package.json
  pyproject.toml
  yarn.lock
Labels: enhancement

#28 Add config files to deploy to Vercel with the COOP / COEP headers
  README.md
  deploy.sh
  requirements-deploy.txt
  vercel.json
Labels: maintenance

#29 Update link to the demo, add demo files
  README.md
  demo/contents/fact.lua
  demo/contents/months.txt
  deploy.sh
Labels: documentation

#30 Update to cockle 0.0.10
  README.md
  demo/contents/months.txt
  package.json
  yarn.lock
Labels: enhancement

#31 Support use of em-forge wasm files in standalone JupyterLite deployment
  .gitignore
  jupyterlite_terminal/add_on.py
Labels: enhancement
